"""empty message

Revision ID: 042d39143291
Revises: 3a6e9da6c41d
Create Date: 2026-05-11 20:07:30.066682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042d39143291'
down_revision: Union[str, Sequence[str], None] = '3a6e9da6c41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('evaluations_assignment_id_jury_id_submission_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['jury_id', 'submission_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('evaluations_assignment_id_jury_id_submission_id_key'), ['assignment_id', 'jury_id', 'submission_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
