"""empty message

Revision ID: 0a7a46f486f9
Revises: dfc9ca7d5a57
Create Date: 2026-05-09 23:21:36.265107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7a46f486f9'
down_revision: Union[str, Sequence[str], None] = 'dfc9ca7d5a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_evaluation_categories',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_evaluation_criteria',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['task_evaluation_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jury_assignments',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('jury_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jury_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'jury_id')
    )
    op.create_table('criterion_scores',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['task_evaluation_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'criterion_id')
    )
    op.drop_table('evaluation_requirements')
    op.drop_table('requirement_evaluations')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('evaluations_submission_id_jury_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['assignment_id'])
        batch_op.drop_constraint(batch_op.f('evaluations_submission_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'submissions', ['submission_id'], ['team_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'jury_assignments', ['assignment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('submission_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('submission_urls_submission_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'submissions', ['submission_id'], ['team_id'], ondelete='CASCADE')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluation_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('min_reviews_per_submission', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('score_scale_max', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('leaderboard_visibility', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('leaderboard_visibility')
        batch_op.drop_column('score_scale_max')
        batch_op.drop_column('min_reviews_per_submission')
        batch_op.drop_column('evaluation_deadline')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('submission_urls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('submission_urls_submission_id_fkey'), 'submissions', ['submission_id'], ['team_id'], ondelete='CASCADE')
        batch_op.drop_column('id')
        batch_op.drop_column('value')

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('evaluations_submission_id_fkey'), 'submissions', ['submission_id'], ['team_id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('evaluations_submission_id_jury_id_key'), ['submission_id', 'jury_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('comment')
        batch_op.drop_column('assignment_id')

    op.create_table('evaluation_requirements',
    sa.Column('requirement_evaluation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requirement_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['requirement_evaluation_id'], ['requirement_evaluations.id'], name=op.f('evaluation_requirements_requirement_evaluation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['task_requirement_options.name'], name=op.f('evaluation_requirements_requirement_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requirement_evaluation_id', 'requirement_id', name=op.f('evaluation_requirements_pkey'))
    )
    op.create_table('requirement_evaluations',
    sa.Column('evaluation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('requirement_evaluations_evaluation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('requirement_evaluations_pkey'))
    )
    op.drop_table('criterion_scores')
    op.drop_table('jury_assignments')
    op.drop_table('task_evaluation_criteria')
    op.drop_table('task_evaluation_categories')
    # ### end Alembic commands ###
