"""empty message

Revision ID: 1afa2bfb3587
Revises: b6b9a8bb78e1
Create Date: 2026-03-02 19:58:36.054914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afa2bfb3587'
down_revision: Union[str, Sequence[str], None] = 'b6b9a8bb78e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_requirement_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'task_requirement_categories', ['main_id'], ['name'])
        batch_op.drop_column('category_id')

    with op.batch_alter_table('task_requirement_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'task_requirement_categories', ['category_id'], ['name'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('captain_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['team_email'])
        batch_op.create_unique_constraint(None, ['contact_info'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tournaments', ['tournament_id'], ['id'])
        batch_op.create_foreign_key(None, 'team_members', ['captain_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.alter_column('active_task_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('cleated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.alter_column('active_task_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'team_members', ['captain_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('captain_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task_requirement_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'task_statuses', ['category_id'], ['name'])

    with op.batch_alter_table('task_requirement_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'task_requirement_categories', ['category_id'], ['name'])

    # ### end Alembic commands ###
