"""empty message

Revision ID: 2e9ac7d1edd6
Revises: 3c3dbf9eab90
Create Date: 2026-04-10 10:07:45.093103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9ac7d1edd6'
down_revision: Union[str, Sequence[str], None] = '3c3dbf9eab90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('discord', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('discord')
        batch_op.drop_column('github')
        batch_op.drop_column('telegram')

    # ### end Alembic commands ###
