"""empty message

Revision ID: 3191704e4d9a
Revises: d146519cd8df
Create Date: 2026-05-03 20:44:22.136819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3191704e4d9a'
down_revision: Union[str, Sequence[str], None] = 'd146519cd8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'news_categories', ['category_name'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_task_tournament', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE', use_alter=True)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_teammember_team', 'teams', ['team_id'], ['id'], ondelete='CASCADE', use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teammember_team', type_='foreignkey')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_tournament', type_='foreignkey')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
