"""додано_нові_таблиці

Revision ID: 395793e08475
Revises: 3191704e4d9a
Create Date: 2026-05-04 13:53:34.804438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395793e08475'
down_revision: Union[str, Sequence[str], None] = '3191704e4d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('evaluations_jury_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('evaluations_submission_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'submissions', ['submission_id'], ['team_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['jury_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('news_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_categories_name'), ['name'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('notifications_body_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('requirement_evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('requirement_evaluations_evaluation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('role_request_info', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('role_request_info_option_name_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('role_request_info_request_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'role_request_info_options', ['option_name'], ['name'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'role_requests', ['request_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('role_requests_role_name_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('role_requests_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_name'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('submission_urls', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('submission_urls_url_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('submission_urls_submission_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'submission_url_options', ['url_id'], ['name'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'submissions', ['submission_id'], ['team_id'], ondelete='CASCADE')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('submissions_team_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_requirement_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_requirement_categories_main_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task_requirement_categories', ['main_id'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('task_requirement_options', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_requirement_options_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task_requirement_categories', ['category_id'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tasks_status_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task_statuses', ['status_id'], ['name'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_task_tournament', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE', use_alter=True)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('team_members_tournament_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_teammember_team', 'teams', ['team_id'], ['id'], ondelete='CASCADE', use_alter=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teams_tournament_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tournaments_status_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tournaments_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tournament_status_options', ['status_id'], ['name'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tournaments_creator_id_fkey'), 'users', ['creator_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tournaments_status_id_fkey'), 'tournament_status_options', ['status_id'], ['name'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teams_tournament_id_fkey'), 'tournaments', ['tournament_id'], ['id'])

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teammember_team', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('team_members_tournament_id_fkey'), 'tournaments', ['tournament_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_tournament', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tasks_status_id_fkey'), 'task_statuses', ['status_id'], ['name'])

    with op.batch_alter_table('task_requirement_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_requirement_options_category_id_fkey'), 'task_requirement_categories', ['category_id'], ['name'])

    with op.batch_alter_table('task_requirement_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_requirement_categories_main_id_fkey'), 'task_requirement_categories', ['main_id'], ['name'])

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('submissions_team_id_fkey'), 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('submission_urls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('submission_urls_submission_id_fkey'), 'submissions', ['submission_id'], ['team_id'])
        batch_op.create_foreign_key(batch_op.f('submission_urls_url_id_fkey'), 'submission_url_options', ['url_id'], ['name'])

    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('role_requests_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('role_requests_role_name_fkey'), 'roles', ['role_name'], ['name'])

    with op.batch_alter_table('role_request_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('role_request_info_request_id_fkey'), 'role_requests', ['request_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('role_request_info_option_name_fkey'), 'role_request_info_options', ['option_name'], ['name'])

    with op.batch_alter_table('requirement_evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('requirement_evaluations_evaluation_id_fkey'), 'evaluations', ['evaluation_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('notifications_body_key'), ['body'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('news_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_categories_name'))

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('evaluations_submission_id_fkey'), 'submissions', ['submission_id'], ['team_id'])
        batch_op.create_foreign_key(batch_op.f('evaluations_jury_id_fkey'), 'users', ['jury_id'], ['id'])

    # ### end Alembic commands ###
