"""empty message

Revision ID: 3c3dbf9eab90
Revises: 8bb9c2b1a990
Create Date: 2026-04-10 10:01:36.288160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3dbf9eab90'
down_revision: Union[str, Sequence[str], None] = '8bb9c2b1a990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_people_in_team', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_people_in_team', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_teams', sa.Integer(), nullable=False))
        batch_op.drop_column('max_team')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_team', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('max_teams')
        batch_op.drop_column('max_people_in_team')
        batch_op.drop_column('min_people_in_team')

    # ### end Alembic commands ###
