"""empty message

Revision ID: 58d30e2d08d7
Revises: 6175928612e4
Create Date: 2026-05-11 20:02:41.760584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d30e2d08d7'
down_revision: Union[str, Sequence[str], None] = '6175928612e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('evaluations_assignment_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['assignment_id', 'jury_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('evaluations_assignment_id_key'), ['assignment_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
