"""empty message

Revision ID: 5b67e3a0a3b6
Revises: 7b2a5bd55133
Create Date: 2026-04-11 22:56:15.825841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b67e3a0a3b6'
down_revision: Union[str, Sequence[str], None] = '7b2a5bd55133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('educational_institution',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('educational_institution',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
