"""Add JuryAssignmentStatusOption table

Revision ID: 641c9fa7192e
Revises: 042d39143291
Create Date: 2026-05-12 08:35:01.926903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641c9fa7192e'
down_revision: Union[str, Sequence[str], None] = '042d39143291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jury_assignment_statuses',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('jury_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.String(), nullable=False, server_default='assigned'))
        batch_op.create_foreign_key(None, 'jury_assignment_statuses', ['status_id'], ['name'], ondelete='CASCADE')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jury_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')

    op.drop_table('jury_assignment_statuses')
    # ### end Alembic commands ###
