"""empty message

Revision ID: 6470c1db43a6
Revises: 34dab362d59d
Create Date: 2026-04-26 12:51:44.957378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6470c1db43a6'
down_revision: Union[str, Sequence[str], None] = '34dab362d59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_status_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_status_options_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_status_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_status_options_name'))

    # ### end Alembic commands ###
