"""empty message

Revision ID: 7145b4774739
Revises: 3086dc6c8e3b
Create Date: 2026-05-12 17:56:17.608823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7145b4774739'
down_revision: Union[str, Sequence[str], None] = '3086dc6c8e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_leaderboard_visible', sa.Boolean(), nullable=False))
        batch_op.drop_column('leaderboard_visibility')
        batch_op.drop_column('score_scale_max')
        batch_op.drop_column('evaluation_deadline')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluation_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('score_scale_max', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('leaderboard_visibility', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_leaderboard_visible')
        batch_op.drop_column('max_score')

    # ### end Alembic commands ###
