"""empty message

Revision ID: 7b2a5bd55133
Revises: f4c68efdd5a5
Create Date: 2026-04-11 20:57:59.532604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2a5bd55133'
down_revision: Union[str, Sequence[str], None] = 'f4c68efdd5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_team_member_email', ['team_id', 'email'])
        batch_op.create_unique_constraint('uq_team_member_telegram', ['team_id', 'telegram'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_member_telegram', type_='unique')
        batch_op.drop_constraint('uq_team_member_email', type_='unique')

    # ### end Alembic commands ###
