"""empty message

Revision ID: 9f92bb2d0e7c
Revises: 041a22bc2dd7
Create Date: 2026-05-10 08:10:15.499841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f92bb2d0e7c'
down_revision: Union[str, Sequence[str], None] = '041a22bc2dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'task_id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jury_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('submission_urls', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_urls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('jury_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('submissions')
    # ### end Alembic commands ###
