"""empty message

Revision ID: a0333f6fca33
Revises: 0ce731a3518f
Create Date: 2026-04-23 23:28:10.312301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0333f6fca33'
down_revision: Union[str, Sequence[str], None] = '0ce731a3518f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['contact_info', 'tournament_id'])

    with op.batch_alter_table('tournament_status_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('tournament_status_options_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tournament_status_options_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_status_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_status_options_name'))
        batch_op.create_unique_constraint(batch_op.f('tournament_status_options_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('display_name')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
