"""add description to submission

Revision ID: b27b4cc1c2d1
Revises: 1c54e936c072
Create Date: 2026-05-06 22:48:21.216312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27b4cc1c2d1'
down_revision: Union[str, Sequence[str], None] = '1c54e936c072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_value', sa.String(), nullable=False))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_task_tournament', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE', use_alter=True)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_teammember_team', 'teams', ['team_id'], ['id'], ondelete='CASCADE', use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teammember_team', type_='foreignkey')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_tournament', type_='foreignkey')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('submission_urls', schema=None) as batch_op:
        batch_op.drop_column('url_value')

    # ### end Alembic commands ###
