"""empty message

Revision ID: b6b9a8bb78e1
Revises: 
Create Date: 2026-03-02 19:57:51.433308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b9a8bb78e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_requirement_categories', sa.Column('main_id', sa.String(), nullable=True))
    op.drop_constraint(None, 'task_requirement_categories', type_='foreignkey')
    op.create_foreign_key(None, 'task_requirement_categories', 'task_requirement_categories', ['main_id'], ['name'])
    op.drop_column('task_requirement_categories', 'category_id')
    op.drop_constraint(None, 'task_requirement_options', type_='foreignkey')
    op.create_foreign_key(None, 'task_requirement_options', 'task_requirement_categories', ['category_id'], ['name'])
    op.alter_column('teams', 'captain_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'teams', ['team_email'])
    op.create_unique_constraint(None, 'teams', ['contact_info'])
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'team_members', ['captain_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teams', 'tournaments', ['tournament_id'], ['id'])
    op.alter_column('tournaments', 'active_task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('users', 'cleated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cleated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('users', 'created_at')
    op.alter_column('tournaments', 'active_task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'team_members', ['captain_id'], ['id'])
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    op.alter_column('teams', 'captain_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'task_requirement_options', type_='foreignkey')
    op.create_foreign_key(None, 'task_requirement_options', 'task_statuses', ['category_id'], ['name'])
    op.add_column('task_requirement_categories', sa.Column('category_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'task_requirement_categories', type_='foreignkey')
    op.create_foreign_key(None, 'task_requirement_categories', 'task_requirement_categories', ['category_id'], ['name'])
    op.drop_column('task_requirement_categories', 'main_id')
    # ### end Alembic commands ###
