"""empty message

Revision ID: c93036e26c52
Revises: 9c3d5ce955b1
Create Date: 2026-03-08 22:01:28.106624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93036e26c52'
down_revision: Union[str, Sequence[str], None] = '9c3d5ce955b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_task_tournament', 'tournaments', ['tournament_id'], ['id'], use_alter=True)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_teammember_team', 'teams', ['team_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teammember_team', type_='foreignkey')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_tournament', type_='foreignkey')

    # ### end Alembic commands ###
