"""empty message

Revision ID: cd57b38a80ee
Revises: 6470c1db43a6
Create Date: 2026-04-26 12:59:08.074944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd57b38a80ee'
down_revision: Union[str, Sequence[str], None] = '6470c1db43a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tournaments_active_task_id_fkey'), type_='foreignkey')
        batch_op.drop_column('active_task_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tournaments_active_task_id_fkey'), 'tasks', ['active_task_id'], ['id'])

    # ### end Alembic commands ###
