"""empty message

Revision ID: e15113d4ca9c
Revises: f5889dcdd5c3
Create Date: 2026-04-04 12:47:44.040902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15113d4ca9c'
down_revision: Union[str, Sequence[str], None] = 'f5889dcdd5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # role_requests: migrate FK from role_id (int) to role_name (str)
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(), nullable=True))

    op.execute(
        sa.text(
            """
            UPDATE role_requests rr
            SET role_name = r.name
            FROM roles r
            WHERE rr.role_id = r.id
            """
        )
    )

    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('role_requests_role_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('role_requests_role_name_fkey'), 'roles', ['role_name'], ['name']
        )
        batch_op.alter_column('role_name', existing_type=sa.String(), nullable=False)
        batch_op.drop_column('role_id')

    # user_roles: migrate FK and PK to use role_name (str)
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(), nullable=True))

    op.execute(
        sa.text(
            """
            UPDATE user_roles ur
            SET role_name = r.name
            FROM roles r
            WHERE ur.role_id = r.id
            """
        )
    )

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_roles_pkey'), type_='primary')
        batch_op.drop_constraint(batch_op.f('user_roles_role_id_fkey'), type_='foreignkey')
        batch_op.alter_column('role_name', existing_type=sa.String(), nullable=False)
        batch_op.drop_column('role_id')
        batch_op.create_foreign_key(
            batch_op.f('user_roles_role_name_fkey'), 'roles', ['role_name'], ['name'], ondelete='CASCADE'
        )
        batch_op.create_primary_key(batch_op.f('user_roles_pkey'), ['user_id', 'role_name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # user_roles: revert FK/PK to role_id (int)
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.execute(
        sa.text(
            """
            UPDATE user_roles ur
            SET role_id = r.id
            FROM roles r
            WHERE ur.role_name = r.name
            """
        )
    )

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_roles_pkey'), type_='primary')
        batch_op.drop_constraint(batch_op.f('user_roles_role_name_fkey'), type_='foreignkey')
        batch_op.alter_column('role_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('role_name')
        batch_op.create_foreign_key(
            batch_op.f('user_roles_role_id_fkey'), 'roles', ['role_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.create_primary_key(batch_op.f('user_roles_pkey'), ['user_id', 'role_id'])

    # role_requests: revert FK to role_id (int)
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.execute(
        sa.text(
            """
            UPDATE role_requests rr
            SET role_id = r.id
            FROM roles r
            WHERE rr.role_name = r.name
            """
        )
    )

    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('role_requests_role_name_fkey'), type_='foreignkey')
        batch_op.alter_column('role_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('role_name')
        batch_op.create_foreign_key(batch_op.f('role_requests_role_id_fkey'), 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###
