"""empty message

Revision ID: eb2f31fb86a1
Revises: 5b67e3a0a3b6
Create Date: 2026-04-13 21:50:54.720031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2f31fb86a1'
down_revision: Union[str, Sequence[str], None] = '5b67e3a0a3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_body_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('notifications_body_key'), ['body'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
