"""empty message

Revision ID: f4c68efdd5a5
Revises: 765a01d9d040
Create Date: 2026-04-11 20:43:37.420276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c68efdd5a5'
down_revision: Union[str, Sequence[str], None] = '765a01d9d040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('tournament_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('team_members_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('team_members_telegram_username_key'), type_='unique')
        batch_op.create_unique_constraint('uq_tournament_member_email', ['tournament_id', 'email'])
        batch_op.create_unique_constraint('uq_tournament_member_telegram', ['tournament_id', 'telegram'])
        batch_op.create_foreign_key(None, 'tournaments', ['tournament_id'], ['id'])
        batch_op.drop_column('telegram_username')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_tournament_member_telegram', type_='unique')
        batch_op.drop_constraint('uq_tournament_member_email', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('team_members_telegram_username_key'), ['telegram_username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('team_members_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('tournament_id')
        batch_op.drop_column('telegram')

    # ### end Alembic commands ###
