"""empty message

Revision ID: fad843168dc7
Revises: b09774274996
Create Date: 2026-04-02 21:27:33.721263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad843168dc7'
down_revision: Union[str, Sequence[str], None] = 'b09774274996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_request_info_options',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('submission_url_options',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('role_request_info',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(length=4096), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_name'], ['role_request_info_options.name'], ),
    sa.ForeignKeyConstraint(['request_id'], ['role_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('evaluations',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('jury_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jury_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'jury_id')
    )
    op.create_table('submission_urls',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.team_id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['submission_url_options.name'], ),
    sa.PrimaryKeyConstraint('submission_id', 'url_id')
    )
    op.create_table('requirement_evaluations',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_requirements',
    sa.Column('requirement_evaluation_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_evaluation_id'], ['requirement_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['task_requirement_options.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requirement_evaluation_id', 'requirement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_requirements')
    op.drop_table('requirement_evaluations')
    op.drop_table('submission_urls')
    op.drop_table('evaluations')
    op.drop_table('submissions')
    op.drop_table('role_request_info')
    op.drop_table('submission_url_options')
    op.drop_table('role_request_info_options')
    # ### end Alembic commands ###
